version: '3'
services:
  api:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    environment: 
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2